-SELECT * FROM pizza_sales

--- TOTAL REVENUE--

SELECT  SUM(TOTAL_PRICE) AS TOTAL_REVENUE

     FROM pizza_sales

SELECT* FROM pizza_sales

 AVERAGE ORDER VALUE ---


SELECT SUM(TOTAL_PRICE)/COUNT(DISTINCT ORDER_ID)  AS AVERAGE_ORDERVALUE FROM pizza_sales


---TOTAL PIZZA SOLD--

SELECT SUM(QUANTITY) AS TOTAL_QUANTITY

FROM PIZZA_SALES

TOTAL ORDER PLACE --

SELECT * FROM PIZZA_SALES

SELECT COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDER FROM PIZZA_SALES

--AVERAGE PIZZA PER ORDERE---

SELECT * FROM pizza_sales

SELECT CAST(SUM(QUANTITY) AS decimal (10,2)) / 
CAST (COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) 
FROM pizza_sales
--FOR CHART --
SELECT DATENAME(DW ,ORDER_DATE) AS ORDER_DAY , COUNT(DISTINCT ORDER_ID ) AS TOTAL_ORDER

FROM pizza_sales

GROUP BY DATENAME(DW ,ORDER_DATE)

-----TREND IN MONTHS-----

SELECT DATENAME(MONTH , ORDER_DATE) AS MONTHS ,COUNT(DISTINCT ORDER_ID )AS TOTAL_ORDER 

FROM pizza_sales

GROUP BY DATENAME(MONTH , ORDER_DATE)

ORDER BY TOTAL_ORDER DESC

---TO GET CATEGORY WISE CONTRIBUTION IN PERCENTAGE------

SELECT PIZZA_CATEGORY ,cast (SUM(TOTAL_PRICE) *100 /( SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES ) as decimal (10,2)) AS PCT

FROM PIZZA_SALES 

GROUP BY PIZZA_CATEGORY 

---NEXT BASED ON SIZE ---

select * from pizza_sales

select pizza_size , cast (sum(total_price) as  decimal(10,2)) as  totalsales ,

cast (sum(total_price)*100 / (select sum(total_price)  from pizza_sales) as decimal(10,2)) as PCT 

from pizza_sales

 group by pizza_size

--top 5  PIZZA NAME order --

select TOP 5 pizza_name ,(COUNT (ORDER_ID)) as totalORDER

from pizza_sales 

GROUP BY PIZZA_NAME

ORDER BY totalORDER  DESC
